export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';

export const ADD_CONNECTION = 'ADD_CONNECTION';
export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
export const SET_CONNECTIONS = 'SET_CONNECTIONS';

export const ADD_CRED_EXCHANGE = 'ADD_CRED_EXCHANGE';
export const UPDATE_CRED_EXCHANGE = 'UPDATE_CRED_EXCHANGE';
export const REMOVE_CRED_EXCHANGE = 'REMOVE_CRED_EXCHANGE';
export const SET_CRED_EXCHANGES = 'SET_CRED_EXCHANGES';

export const ADD_PRES_EXCHANGE = 'ADD_PRES_EXCHANGE';
export const UPDATE_PRES_EXCHANGE = 'UPDATE_PRES_EXCHANGE';
export const REMOVE_PRES_EXCHANGE = 'REMOVE_PRES_EXCHANGE';
export const SET_PRES_EXCHANGES = 'SET_PRES_EXCHANGES';
